name: deploy-infra.yml

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read


jobs:
  terragrunt-plan:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Terragrunt Plan (on push to main)
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      GIT_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.14.5'

      - name: Setup SSH agent for git
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.GIT_SSH_KEY }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume:  ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt init
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_subcommand: 'run-all init --terragrunt-non-interactive'
          tf_actions_working_dir: src

      - name: Terragrunt plan
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_subcommand: 'run-all plan --terragrunt-non-interactive'
          tf_actions_working_dir: src

  terragrunt-apply:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Terragrunt Apply (manual)
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      GIT_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      TG_LOG: debug
      TG_LOG_PATH: .terragrunt.log

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.14.5'

      - name: Setup SSH agent for git
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.GIT_SSH_KEY }}


      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume:  ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt init
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_subcommand: 'run-all init --terragrunt-non-interactive'
          tf_actions_working_dir: src

      - name: Terragrunt run-all apply (auto-approve)
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_subcommand: 'run-all apply --terragrunt-non-interactive --auto-approve'
          tf_actions_working_dir: src
